### ISSUE TITLE
Module doesn't work on M1 Macbook due to incorrect architecture & URL

### ISSUE THREAD

**Issue by asachs01** [nikku/hugo-cli#35]
__Describe the Bug__

`hugo-cli` doesn't work when being invoked on an M1 Macbook pro

__Steps to Reproduce__

<details>
  <summary><b>Full stack trace</b></summary>

```
test@test-mac sensu-docs % yarn
yarn install v1.22.19
info No lockfile found.
[1/5] 🔍  Validating package.json...
[2/5] 🔍  Resolving packages...
warning cssnano > cssnano-preset-default > postcss-svgo > svgo@1.3.2: This SVGO version is no longer supported. Upgrade to v2.x.x.
warning cssnano > cssnano-preset-default > postcss-svgo > svgo > stable@0.1.8: Modern JS already guarantees Array#sort() is a stable sort, so this library is deprecated. See the compatibility table on MDN: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort#browser_compatibility
warning node-sass > request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
warning node-sass > request > uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
warning node-sass > request > har-validator@5.1.5: this library is no longer supported
[3/5] 🚚  Fetching packages...
[4/5] 🔗  Linking dependencies...
[5/5] 🔨  Building fresh packages...
success Saved lockfile.
$ grunt
Running "env:dev" (env) task
Running "env:dev" (env) task
Running "print-hugo-version" task
INFO hugo not found. Attempting to fetch it...
ERROR failed to download hugo: HTTPError: Response code 404 (Not Found)
failed to grab hugo :-(
GotError [HTTPError]: Response code 404 (Not Found)
    at EventEmitter.<anonymous> (/Users/test/sensu-docs/node_modules/got/source/as-stream.js:35:24)
    at EventEmitter.emit (node:events:513:28)
    at module.exports (/Users/test/sensu-docs/node_modules/got/source/get-response.js:22:10)
    at ClientRequest.handleResponse (/Users/test/sensu-docs/node_modules/got/source/request-as-event-emitter.js:155:5)
    at Object.onceWrapper (node:events:628:26)
    at ClientRequest.emit (node:events:525:35)
    at origin.emit (/Users/test/sensu-docs/node_modules/@szmarczak/http-timer/source/index.js:37:11)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (node:_http_client:693:27)
    at HTTPParser.parserOnHeadersComplete (node:_http_common:117:17)
    at TLSSocket.socketOnData (node:_http_client:534:22) {
  host: 'github.com',
  hostname: 'github.com',
  method: 'GET',
  path: '/gohugoio/hugo/releases/download/v0.101.0/hugo_0.101.0_macOS_ARM.tar.gz',
  socketPath: undefined,
  protocol: 'https:',
  url: 'https://github.com/gohugoio/hugo/releases/download/v0.101.0/hugo_0.101.0_macOS_ARM.tar.gz',
  gotOptions: {
    path: '/gohugoio/hugo/releases/download/v0.101.0/hugo_0.101.0_macOS_ARM.tar.gz',
    protocol: 'https:',
    slashes: true,
    auth: null,
    host: 'github.com',
    port: null,
    hostname: 'github.com',
    hash: null,
    search: null,
    query: null,
    pathname: '/gohugoio/hugo/releases/download/v0.101.0/hugo_0.101.0_macOS_ARM.tar.gz',
    href: 'https://github.com/gohugoio/hugo/releases/download/v0.101.0/hugo_0.101.0_macOS_ARM.tar.gz',
    retry: {
      retries: [Function (anonymous)],
      methods: [Set],
      statusCodes: [Set],
      errorCodes: [Set]
    },
    headers: {
      'user-agent': 'got/9.6.0 (https://github.com/sindresorhus/got)',
      'accept-encoding': 'gzip, deflate'
    },
    hooks: {
      beforeRequest: [],
      beforeRedirect: [],
      beforeRetry: [],
      afterResponse: [],
      beforeError: [],
      init: []
    },
    decompress: true,
    throwHttpErrors: true,
    followRedirect: true,
    stream: true,
    form: false,
    json: false,
    cache: false,
    useElectronNet: false,
    method: 'GET'
  },
  statusCode: 404,
  statusMessage: 'Not Found',
  headers: {
    server: 'GitHub.com',
    date: 'Mon, 17 Oct 2022 14:08:22 GMT',
    'content-type': 'text/plain; charset=utf-8',
    vary: 'X-PJAX, X-PJAX-Container, Turbo-Visit, Turbo-Frame, Accept-Encoding, Accept, X-Requested-With',
    'cache-control': 'no-cache',
    'strict-transport-security': 'max-age=31536000; includeSubdomains; preload',
    'x-frame-options': 'deny',
    'x-content-type-options': 'nosniff',
    'x-xss-protection': '0',
    'referrer-policy': 'no-referrer-when-downgrade',
    'expect-ct': 'max-age=2592000, report-uri="https://api.github.com/_private/browser/errors"',
    'content-security-policy': "default-src 'none'; base-uri 'self'; connect-src 'self'; form-action 'self'; img-src 'self' data:; script-src 'self'; style-src 'unsafe-inline'",
    'content-encoding': 'gzip',
    'content-length': '29',
    'x-github-request-id': 'CA67:6C99:E82772:15F08B2:634D61D6',
    connection: 'close'
  },
  body: undefined
}
Fatal error: Error
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.

% uname -a

Darwin mac 21.6.0 Darwin Kernel Version 21.6.0: Mon Aug 22 20:19:52 PDT 2022; root:xnu-8020.140.49~2/RELEASE_ARM64_T6000 arm64

```

</details>

__Expected Behavior__

`arch_exec` and `arch_dl` should be able to ascertain the difference between `ARM` and `ARM64`

__Environment__

- Host (Browser/Node version), if applicable: [e.g. MS Edge 18, Chrome 69, Node 10 LTS]: Node 18
- OS: [e.g. Windows 7]: MacOS/M1 Macbook
- Library version: [e.g. 2.0.0] 0.11.0

**Comment by nikku** [comment]
Released fix with `v0.11.1`. Thank you!
